# CMake generated Testfile for 
# Source directory: /home/kumaran/git/gromacs/src/gromacs
# Build directory: /home/kumaran/git/gromacs/src/gromacs
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
SUBDIRS(gmxlib)
SUBDIRS(mdlib)
SUBDIRS(listed-forces)
SUBDIRS(commandline)
SUBDIRS(domdec)
SUBDIRS(ewald)
SUBDIRS(fft)
SUBDIRS(gpu_utils)
SUBDIRS(hardware)
SUBDIRS(linearalgebra)
SUBDIRS(math)
SUBDIRS(mdrunutility)
SUBDIRS(mdtypes)
SUBDIRS(random)
SUBDIRS(onlinehelp)
SUBDIRS(options)
SUBDIRS(pbcutil)
SUBDIRS(tables)
SUBDIRS(timing)
SUBDIRS(topology)
SUBDIRS(trajectory)
SUBDIRS(utility)
SUBDIRS(fileio)
SUBDIRS(swap)
SUBDIRS(essentialdynamics)
SUBDIRS(pulling)
SUBDIRS(simd)
SUBDIRS(imd)
SUBDIRS(gmxana)
SUBDIRS(gmxpreprocess)
SUBDIRS(correlationfunctions)
SUBDIRS(statistics)
SUBDIRS(analysisdata)
SUBDIRS(selection)
SUBDIRS(trajectoryanalysis)
SUBDIRS(tools)
